### ISSUE TITLE
Can you please update eslint to latest (9.1), as it doesn't support .js it require .json with new updates

### ISSUE THREAD

**Issue by prabhjotsinghchadha** [hadrysm/nextjs-boilerplate#1436]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

## Expected Behavior

- ESLint should be updated to the latest version (9.1)
- Configuration files should be in .json format

## Current Behavior

- ESLint is using an older version
- Configuration files are in .js format, which is no longer supported in the latest version

## Steps to Reproduce
1. Check the current ESLint version in the project
2. Attempt to use a .js configuration file with the latest ESLint version
3. Observe that the .js configuration file is not recognized or causes errors

**Comment by hadrysm** [comment]
Hi @prabhjotsinghchadha, thanks for the submission. I’ll check it out in the next few days.

**Comment by prabhjotsinghchadha** [comment]
dzięki stary

> Hi @prabhjotsinghchadha, thanks for the submission. I’ll check it out in the next few days.

dzięki stary

**Comment by hadrysm** [comment]
Hi @prabhjotsinghchadha, I have updated Next.js to version 15, which has resolved the ESLint configuration issue. Let me know if you encounter any further problems.

**Comment by prabhjotsinghchadha** [comment]
Thanks alot @hadrysm
